QuikForm.WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using QuikForm.Business.Contracts.Business;
using QuikForm.Business.Contracts.Responses.Forms;
using QuikForm.Entities;
using QuikForm.WebApp.Mappers.Forms;
using QuikForm.WebApp.Models;
using QuikForm.WebApp.Models.Forms;
using System.Diagnostics;

namespace QuikForm.WebApp.Controllers;
public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly IFormBusiness _formBusiness;
    private readonly IFormMapper _formMapper;

    public HomeController(ILogger<HomeController> logger, IFormBusiness formBusiness, IFormMapper formMapper)
    {
        _logger = logger;
        _formBusiness = formBusiness;
        _formMapper = formMapper;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        FormListsViewModel formListsViewModel = new FormListsViewModel();

        List<FormResponse> formResponsePublishedAts = await _formBusiness.GetAllPublishedAndNotClosedByPublishedAtDescAsync();
        List<FormViewModel> formsPublishedAtViewModel = formResponsePublishedAts.Select(f => _formMapper.ToFormViewModel(f)).ToList();
        formListsViewModel.FormsPublishedAtViewModel = formsPublishedAtViewModel;

        List<FormResponse> formsClosedAt = await _formBusiness.GetAllClosedByClosedAtDescAsync();
        List<FormViewModel> formsClosedAtViewModel = formsClosedAt.Select(f => _formMapper.ToFormViewModel(f)).ToList();
        formListsViewModel.FormsClosedAtViewModel = formsClosedAtViewModel;

        return View(formListsViewModel);
    }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

QuikForm.WebApp/Views/Shared/Components/FormFull/FormFullViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using QuikForm.WebApp.Models.Forms;
using System.ComponentModel;

namespace QuikForm.WebApp.Views.Shared.Components.FormFull;

public class FormFullViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(FormViewModel formViewModel, bool isSubmit = false)
    {
        ViewBag.IsSubmit = isSubmit;
        return View(formViewModel);
    }
}

QuikForm.WebApp/Views/Shared/Components/FormShort/FormShortViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using QuikForm.WebApp.Models.Forms;

namespace QuikForm.WebApp.Views.Shared.Components.FormShort;

public class FormShortViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(FormViewModel formViewModel)
    {
        return View(formViewModel);
    }
}

QuikForm.WebApp/Views/Home/Index.cshtml
@model FormListsViewModel


<section class="grid">
    <div class="text-center">
        <h2 class="">Bienvenue sur</h2>
        <p class="quikform">
            <img src="/images/file-logo.svg" class="logo-file" />
            <span class="quikform-home-link">QuikForm</span>
        </p>
        <p>Votre formulaire à portée de main </p>
    </div>
    <div></div>
</section>
<section>
    <h2>Répondez à nos sondages !</h2>
    @if (Model.FormsPublishedAtViewModel.Count > 0)
    {
        <vc:form-short-list form-view-models="Model.FormsPublishedAtViewModel" />
    }
    else
    {
        <p>Aucun formulaire publié</p>
    }



</section>

<section>
    <h2>Découvrez les derniers résultats</h2>
    @if (Model.FormsClosedAtViewModel.Count > 0)
    {
        <vc:form-short-list form-view-models="Model.FormsClosedAtViewModel" />
    }
    else
    {
        <p>Aucun formulaire clôturé</p>
    }
</section>

QuikForm.WebApp/Views/Home/Submit.cshtml
@model FormViewModel

<form asp-controller="Home" asp-action="Submit">
    <vc:form-full form-view-model="Model" />
    <section class="user-validation">
        <div class="action">
            <button class="primary">Envoyer</button>
        </div>
    </section>
</form>